Stabilize uavcan.node.port.List
OpenCyphal/public_regulated_data_types pull request #138
Opened 2023-02-11 16:04 UTC by pavel-kirienko

Closes #134; the other v0 types can be stabilized after the release.

2023-02-15 12:24 UTC, pavel-kirienko commented
@thirtytwobits nudge

2023-02-16 01:15 UTC, thirtytwobits commented
Sorry... 👀

2023-02-16 01:23 UTC, thirtytwobits requested changes

2023-02-16 01:23 UTC, thirtytwobits commented on uavcan/node/port/SubjectIDList.1.0.dsdl
> +uavcan.primitive.Empty.1.0 total
Wait...how am I supposed t use this?

2023-02-16 01:23 UTC, thirtytwobits commented on uavcan/node/port/SubjectIDList.1.0.dsdl
> +bool[CAPACITY] mask
If I use the sparse_list am I required to also set the mask? There's a bit of ambiguity here on the requirements for using this type.

2023-02-16 01:37 UTC, pavel-kirienko commented
It's a union, only one field is active at any moment. The empty field is
just a tag.

On Thu, Feb 16, 2023, 03:23 Scott Dixon ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In uavcan/node/port/SubjectIDList.1.0.dsdl
> <https://github.com/OpenCyphal/public_regulated_data_types/pull/138#discussion_r1107909990>
> :
>
> > +# A list of subject identifiers.
> +# The range of subject-ID is large, so using a fixed-size bitmask would make this type difficult to handle on
> +# resource-constrained systems. To address that, we provide two extra options: a simple variable-length list,
> +# and a special case that indicates that every subject-ID is in use.
> +
> ***@***.***
> +
> +uint16 CAPACITY = SubjectID.1.0.MAX + 1
> +
> +bool[CAPACITY] mask
> +# The index represents the identifier value. True -- present/used. False -- absent/unused.
> +
> +SubjectID.1.0[<256] sparse_list
> +# A list of identifiers that can be used instead of the mask if most of the identifiers are unused.
> +
> +uavcan.primitive.Empty.1.0 total
>
> Wait...how am I supposed t use this?
> ------------------------------
>
> In uavcan/node/port/SubjectIDList.1.0.dsdl
> <https://github.com/OpenCyphal/public_regulated_data_types/pull/138#discussion_r1107910626>
> :
>
> > @@ -0,0 +1,19 @@
> +# A list of subject identifiers.
> +# The range of subject-ID is large, so using a fixed-size bitmask would make this type difficult to handle on
> +# resource-constrained systems. To address that, we provide two extra options: a simple variable-length list,
> +# and a special case that indicates that every subject-ID is in use.
> +
> ***@***.***
> +
> +uint16 CAPACITY = SubjectID.1.0.MAX + 1
> +
> +bool[CAPACITY] mask
>
> If I use the sparse_list am I required to also set the mask? There's a bit
> of ambiguity here on the requirements for using this type.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenCyphal/public_regulated_data_types/pull/138#pullrequestreview-1300612259>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAZFIZDJ2FMWISSXCSRTZLDWXV6QBANCNFSM6AAAAAAUYYTUJY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2023-02-16 01:47 UTC, thirtytwobits commented
> It's a union, only one field is active at any moment. The empty field is just a tag.

I'm an idiot. Sorry.

2023-02-16 01:48 UTC, thirtytwobits approved these changes

2023-02-16 01:48 UTC, merged

2023-04-25 07:14 UTC, Alcalalandscapingpavers commented
#140 landscapingpaversalcala.wordpress.com